# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'appmanager.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets
from PySide6.QtCore import Qt
from PySide6.QtWidgets import QStackedWidget


class Ui_appManage(object):
    def setupUi(self, Form):
        Form.setObjectName("AppManageInterface")
        Form.resize(1018, 582)
        self.CardWidget = CardWidget(Form)
        self.CardWidget.setGeometry(QtCore.QRect(0, 0, 381, 581))
        self.CardWidget.setObjectName("CardWidget")

        self.SearchLineEdit = SearchLineEdit(self.CardWidget)
        self.SearchLineEdit.setGeometry(QtCore.QRect(31, 20, 321, 33))
        self.SearchLineEdit.setObjectName("SearchLineEdit")

        self.SegmentedWidget = SegmentedWidget(self.CardWidget)
        self.SegmentedWidget.setGeometry(QtCore.QRect(30, 70, 321, 33))
        self.SegmentedWidget.setObjectName("SegmentedWidget")
        self.stackedWidget = QStackedWidget(self.CardWidget)
        self.allAppInterface = ListWidget(self.CardWidget)
        self.sysAppInterface = ListWidget(self.CardWidget)
        self.userAppInterface = ListWidget(self.CardWidget)
        self.addSubInterface(self.allAppInterface, 'All_App', '全部')
        self.addSubInterface(self.sysAppInterface, 'Sys_App', '系统')
        self.addSubInterface(self.userAppInterface, 'User_App', '用户')
        self.stackedWidget.currentChanged.connect(self.onCurrentIndexChanged)
        self.stackedWidget.setCurrentWidget(self.allAppInterface)
        self.stackedWidget.setGeometry(QtCore.QRect(30, 100, 321, 500))

        self.CardWidget_2 = CardWidget(Form)
        self.CardWidget_2.setGeometry(QtCore.QRect(380, 0, 641, 661))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CardWidget_2.sizePolicy().hasHeightForWidth())
        self.CardWidget_2.setSizePolicy(sizePolicy)
        self.CardWidget_2.setObjectName("CardWidget_2")

        self.StrongBodyLabel = StrongBodyLabel(self.CardWidget_2)
        self.StrongBodyLabel.setGeometry(QtCore.QRect(30, 60, 113, 19))
        self.StrongBodyLabel.setObjectName("StrongBodyLabel")
        self.StrongBodyLabel_2 = StrongBodyLabel(self.CardWidget_2)
        self.StrongBodyLabel_2.setGeometry(QtCore.QRect(30, 110, 113, 19))
        self.StrongBodyLabel_2.setObjectName("StrongBodyLabel_2")
        self.StrongBodyLabel_3 = StrongBodyLabel(self.CardWidget_2)
        self.StrongBodyLabel_3.setGeometry(QtCore.QRect(30, 160, 113, 19))
        self.StrongBodyLabel_3.setObjectName("StrongBodyLabel_3")
        self.StrongBodyLabel_4 = StrongBodyLabel(self.CardWidget_2)
        self.StrongBodyLabel_4.setGeometry(QtCore.QRect(30, 210, 113, 19))
        self.StrongBodyLabel_4.setObjectName("StrongBodyLabel_4")
        self.StrongBodyLabel_5 = StrongBodyLabel(self.CardWidget_2)
        self.StrongBodyLabel_5.setGeometry(QtCore.QRect(30, 260, 113, 19))
        self.StrongBodyLabel_5.setObjectName("StrongBodyLabel_5")
        self.StrongBodyLabel_6 = StrongBodyLabel(self.CardWidget_2)
        self.StrongBodyLabel_6.setGeometry(QtCore.QRect(30, 310, 113, 19))
        self.StrongBodyLabel_6.setObjectName("StrongBodyLabel_6")
        self.StrongBodyLabel_7 = StrongBodyLabel(self.CardWidget_2)
        self.StrongBodyLabel_7.setGeometry(QtCore.QRect(30, 360, 113, 19))
        self.StrongBodyLabel_7.setObjectName("StrongBodyLabel_7")
        self.StrongBodyLabel_8 = StrongBodyLabel(self.CardWidget_2)
        self.StrongBodyLabel_8.setGeometry(QtCore.QRect(30, 410, 113, 19))
        self.StrongBodyLabel_8.setObjectName("StrongBodyLabel_8")
        self.StrongBodyLabel_9 = StrongBodyLabel(self.CardWidget_2)
        self.StrongBodyLabel_9.setGeometry(QtCore.QRect(30, 460, 113, 19))
        self.StrongBodyLabel_9.setObjectName("StrongBodyLabel_9")
        self.download_bt = PrimaryPushButton(self.CardWidget_2)
        self.download_bt.setGeometry(QtCore.QRect(420, 20, 61, 32))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/download.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.download_bt.setIcon(icon)
        self.download_bt.setIconSize(QtCore.QSize(22, 22))
        self.download_bt.setObjectName("download_bt")
        self.download_bt.setStyleSheet("PushButton, ToolButton, ToggleButton, ToggleToolButton {\n"
                                       "    color: black;\n"
                                       "    background: rgba(255, 255, 255, 0.7);\n"
                                       "    border: 1px solid rgba(0, 0, 0, 0.073);\n"
                                       "    border-bottom: 1px solid rgba(0, 0, 0, 0.183);\n"
                                       "    border-radius: 10px;\n"
                                       "    /* font: 14px \'Segoe UI\', \'Microsoft YaHei\'; */\n"
                                       "    padding: 5px 12px 6px 12px;\n"
                                       "    font-size: 1px;\n"
                                       "    outline: none;\n"
                                       "}\n"
                                       "PushButton[hasIcon=false] {\n"
                                       "    padding: 5px 12px 6px 12px;\n"
                                       "}\n"
                                       "PushButton[hasIcon=true] {\n"
                                       "    padding: 5px 12px 6px 25px;\n"
                                       "}\n"
                                       "PushButton:hover, ToolButton:hover, ToggleButton:hover, ToggleToolButton:hover {\n"
                                       "    background: rgba(249, 249, 249, 0.5);\n"
                                       "}\n"
                                       "PushButton:pressed, ToolButton:pressed, ToggleButton:pressed, ToggleToolButton:pressed {\n"
                                       "    color: rgba(0, 0, 0, 0.63);\n"
                                       "    background: rgba(249, 249, 249, 0.3);\n"
                                       "    border-bottom: 1px solid rgba(0, 0, 0, 0.073);\n"
                                       "}\n"
                                       "PushButton:disabled, ToolButton:disabled, ToggleButton:disabled, ToggleToolButton:disabled {\n"
                                       "    color: rgba(0, 0, 0, 0.36);\n"
                                       "    background: rgba(249, 249, 249, 0.3);\n"
                                       "    border: 1px solid rgba(0, 0, 0, 0.06);\n"
                                       "    border-bottom: 1px solid rgba(0, 0, 0, 0.06);\n"
                                       "}\n"
                                       "PrimaryPushButton,\n"
                                       "PrimaryToolButton,\n"
                                       "ToggleButton:checked,\n"
                                       "ToggleToolButton:checked {\n"
                                       "    color: white;\n"
                                       "    background-color: #009faa;\n"
                                       "    border: 1px solid #00a7b3;\n"
                                       "    border-bottom: 1px solid #007780;\n"
                                       "}\n"
                                       "PrimaryPushButton:hover,\n"
                                       "PrimaryToolButton:hover,\n"
                                       "ToggleButton:checked:hover,\n"
                                       "ToggleToolButton:checked:hover {\n"
                                       "    background-color: #00a7b3;\n"
                                       "    border: 1px solid #2daab3;\n"
                                       "    border-bottom: 1px solid #007780;\n"
                                       "}\n"
                                       "ToggleButton:checked:pressed,\n"
                                       "ToggleToolButton:checked:pressed {\n"
                                       "    color: rgba(255, 255, 255, 0.63);\n"
                                       "    background-color: #3eabb3;\n"
                                       "    border: 1px solid #3eabb3;\n"
                                       "}")
        self.uninstall_bt = PrimaryPushButton(self.CardWidget_2)
        self.uninstall_bt.setGeometry(QtCore.QRect(500, 20, 61, 32))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resources/卸载.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.uninstall_bt.setIcon(icon1)
        self.uninstall_bt.setIconSize(QtCore.QSize(20, 20))
        self.uninstall_bt.setObjectName("uninstall_bt")
        self.uninstall_bt.setStyleSheet("PushButton, ToolButton, ToggleButton, ToggleToolButton {\n"
                                         "    color: black;\n"
                                         "    background: rgba(255, 255, 255, 0.7);\n"
                                         "    border: 1px solid rgba(0, 0, 0, 0.073);\n"
                                         "    border-bottom: 1px solid rgba(0, 0, 0, 0.183);\n"
                                         "    border-radius: 10px;\n"
                                         "    /* font: 14px \'Segoe UI\', \'Microsoft YaHei\'; */\n"
                                         "    padding: 5px 12px 6px 12px;\n"
                                         "    font-size: 1px;\n"
                                         "    outline: none;\n"
                                         "}\n"
                                         "PushButton[hasIcon=false] {\n"
                                         "    padding: 5px 12px 6px 12px;\n"
                                         "}\n"
                                         "PushButton[hasIcon=true] {\n"
                                         "    padding: 5px 12px 6px 25px;\n"
                                         "}\n"
                                         "PushButton:hover, ToolButton:hover, ToggleButton:hover, ToggleToolButton:hover {\n"
                                         "    background: rgba(249, 249, 249, 0.5);\n"
                                         "}\n"
                                         "PushButton:pressed, ToolButton:pressed, ToggleButton:pressed, ToggleToolButton:pressed {\n"
                                         "    color: rgba(0, 0, 0, 0.63);\n"
                                         "    background: rgba(249, 249, 249, 0.3);\n"
                                         "    border-bottom: 1px solid rgba(0, 0, 0, 0.073);\n"
                                         "}\n"
                                         "PushButton:disabled, ToolButton:disabled, ToggleButton:disabled, ToggleToolButton:disabled {\n"
                                         "    color: rgba(0, 0, 0, 0.36);\n"
                                         "    background: rgba(249, 249, 249, 0.3);\n"
                                         "    border: 1px solid rgba(0, 0, 0, 0.06);\n"
                                         "    border-bottom: 1px solid rgba(0, 0, 0, 0.06);\n"
                                         "}\n"
                                         "PrimaryPushButton,\n"
                                         "PrimaryToolButton,\n"
                                         "ToggleButton:checked,\n"
                                         "ToggleToolButton:checked {\n"
                                         "    color: white;\n"
                                         "    background-color: #009faa;\n"
                                         "    border: 1px solid #00a7b3;\n"
                                         "    border-bottom: 1px solid #007780;\n"
                                         "}\n"
                                         "PrimaryPushButton:hover,\n"
                                         "PrimaryToolButton:hover,\n"
                                         "ToggleButton:checked:hover,\n"
                                         "ToggleToolButton:checked:hover {\n"
                                         "    background-color: #00a7b3;\n"
                                         "    border: 1px solid #2daab3;\n"
                                         "    border-bottom: 1px solid #007780;\n"
                                         "}\n"
                                         "ToggleButton:checked:pressed,\n"
                                         "ToggleToolButton:checked:pressed {\n"
                                         "    color: rgba(255, 255, 255, 0.63);\n"
                                         "    background-color: #3eabb3;\n"
                                         "    border: 1px solid #3eabb3;\n"
                                         "}")

        self.LineEdit = LineEdit(self.CardWidget_2)
        self.LineEdit.setGeometry(QtCore.QRect(120, 50, 221, 33))
        self.LineEdit.setObjectName("LineEdit")
        self.LineEdit_2 = LineEdit(self.CardWidget_2)
        self.LineEdit_2.setGeometry(QtCore.QRect(120, 100, 221, 33))
        self.LineEdit_2.setObjectName("LineEdit_2")
        self.LineEdit_3 = LineEdit(self.CardWidget_2)
        self.LineEdit_3.setGeometry(QtCore.QRect(120, 150, 221, 33))
        self.LineEdit_3.setObjectName("LineEdit_3")
        self.LineEdit_4 = LineEdit(self.CardWidget_2)
        self.LineEdit_4.setGeometry(QtCore.QRect(120, 200, 221, 33))
        self.LineEdit_4.setObjectName("LineEdit_4")
        self.LineEdit_5 = LineEdit(self.CardWidget_2)
        self.LineEdit_5.setGeometry(QtCore.QRect(120, 250, 221, 33))
        self.LineEdit_5.setObjectName("LineEdit_5")
        self.LineEdit_6 = LineEdit(self.CardWidget_2)
        self.LineEdit_6.setGeometry(QtCore.QRect(120, 300, 221, 33))
        self.LineEdit_6.setObjectName("LineEdit_6")
        self.LineEdit_7 = LineEdit(self.CardWidget_2)
        self.LineEdit_7.setGeometry(QtCore.QRect(120, 350, 221, 33))
        self.LineEdit_7.setObjectName("LineEdit_7")
        self.LineEdit_8 = LineEdit(self.CardWidget_2)
        self.LineEdit_8.setGeometry(QtCore.QRect(120, 410, 221, 33))
        self.LineEdit_8.setObjectName("LineEdit_8")
        self.TextEdit = TextEdit(self.CardWidget_2)
        self.TextEdit.setGeometry(QtCore.QRect(120, 460, 221, 101))
        self.TextEdit.setObjectName("TextEdit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.StrongBodyLabel.setText(_translate("Form", "包名:"))
        self.StrongBodyLabel_2.setText(_translate("Form", "版本名:"))
        self.StrongBodyLabel_3.setText(_translate("Form", "版本号:"))
        self.StrongBodyLabel_4.setText(_translate("Form", "编译SDK:"))
        self.StrongBodyLabel_5.setText(_translate("Form", "最小SDK:"))
        self.StrongBodyLabel_6.setText(_translate("Form", "系统应用:"))
        self.StrongBodyLabel_7.setText(_translate("Form", "签名版本:"))
        self.StrongBodyLabel_8.setText(_translate("Form", "应用大小"))
        self.StrongBodyLabel_9.setText(_translate("Form", "安装路径:"))

    def addSubInterface(self, widget, objectName, text):
        widget.setObjectName(objectName)
        self.stackedWidget.addWidget(widget)
        self.SegmentedWidget.addItem(
            routeKey=objectName,
            text=text,
            onClick=lambda: self.stackedWidget.setCurrentWidget(widget)
        )

    def onCurrentIndexChanged(self, index):
        widget = self.stackedWidget.widget(index)
        self.SegmentedWidget.setCurrentItem(widget.objectName())


from qfluentwidgets import CardWidget, LineEdit, PrimaryPushButton, SearchLineEdit, SegmentedWidget, StrongBodyLabel, \
    TextEdit, ListWidget
