# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tools.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6.QtCore import *  # type: ignore
from PySide6.QtGui import *  # type: ignore
from PySide6.QtWidgets import *  # type: ignore
from PySide6 import QtCore, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1018, 582)
        self.CardWidget = CardWidget(Form)
        layout = QHBoxLayout(Form)
        self.CardWidget.setGeometry(QtCore.QRect(0, 0, 371, 581))
        self.CardWidget.setObjectName("CardWidget")
        self.StrongBodyLabel = StrongBodyLabel(self.CardWidget)
        self.StrongBodyLabel.setGeometry(QtCore.QRect(10, 15, 113, 19))
        self.StrongBodyLabel.setObjectName("StrongBodyLabel")
        self.StrongBodyLabel_2 = StrongBodyLabel(self.CardWidget)
        self.StrongBodyLabel_2.setGeometry(QtCore.QRect(10, 65, 113, 19))
        self.StrongBodyLabel_2.setObjectName("StrongBodyLabel_2")
        self.StrongBodyLabel_3 = StrongBodyLabel(self.CardWidget)
        self.StrongBodyLabel_3.setGeometry(QtCore.QRect(10, 115, 121, 19))
        self.StrongBodyLabel_3.setObjectName("StrongBodyLabel_3")
        self.StrongBodyLabel_6 = StrongBodyLabel(self.CardWidget)
        self.StrongBodyLabel_6.setGeometry(QtCore.QRect(10, 265, 131, 19))
        self.StrongBodyLabel_6.setObjectName("StrongBodyLabel_6")
        self.StrongBodyLabel_7 = StrongBodyLabel(self.CardWidget)
        self.StrongBodyLabel_7.setGeometry(QtCore.QRect(10, 315, 131, 19))
        self.StrongBodyLabel_7.setObjectName("StrongBodyLabel_7")
        self.model = LineEdit(self.CardWidget)
        self.model.setGeometry(QtCore.QRect(200, 10, 161, 40))
        self.model.setReadOnly(True)
        self.model.setObjectName("model")
        self.brand = LineEdit(self.CardWidget)
        self.brand.setGeometry(QtCore.QRect(200, 60, 161, 40))
        self.brand.setReadOnly(True)
        self.brand.setObjectName("brand")
        self.android_version = LineEdit(self.CardWidget)
        self.android_version.setGeometry(QtCore.QRect(200, 110, 161, 40))
        self.android_version.setReadOnly(True)
        self.android_version.setObjectName("android_version")
        self.fingerprint = LineEdit(self.CardWidget)
        self.fingerprint.setGeometry(QtCore.QRect(200, 260, 161, 40))
        self.fingerprint.setReadOnly(True)
        self.fingerprint.setObjectName("fingerprint")
        self.ipv4 = LineEdit(self.CardWidget)
        self.ipv4.setGeometry(QtCore.QRect(200, 310, 161, 40))
        self.ipv4.setReadOnly(True)
        self.ipv4.setObjectName("ipv4")
        self.output_prop = LineEdit(self.CardWidget)
        self.output_prop.setGeometry(QtCore.QRect(200, 460, 161, 40))
        self.output_prop.setText("")
        self.output_prop.setReadOnly(True)
        self.output_prop.setObjectName("output_prop")
        self.search_prop = SearchLineEdit(self.CardWidget)
        self.search_prop.setGeometry(QtCore.QRect(10, 460, 171, 40))
        self.search_prop.setObjectName("search_prop")
        self.StrongBodyLabel_8 = StrongBodyLabel(self.CardWidget)
        self.StrongBodyLabel_8.setGeometry(QtCore.QRect(10, 165, 131, 19))
        self.StrongBodyLabel_8.setObjectName("StrongBodyLabel_8")
        self.sn = LineEdit(self.CardWidget)
        self.sn.setGeometry(QtCore.QRect(200, 160, 161, 40))
        self.sn.setReadOnly(True)
        self.sn.setObjectName("sn")
        self.mac = LineEdit(self.CardWidget)
        self.mac.setGeometry(QtCore.QRect(200, 210, 161, 40))
        self.mac.setReadOnly(True)
        self.mac.setObjectName("mac")
        self.StrongBodyLabel_9 = StrongBodyLabel(self.CardWidget)
        self.StrongBodyLabel_9.setGeometry(QtCore.QRect(10, 215, 131, 19))
        self.StrongBodyLabel_9.setObjectName("StrongBodyLabel_9")
        self.StrongBodyLabel_4 = StrongBodyLabel(self.CardWidget)
        self.StrongBodyLabel_4.setGeometry(QtCore.QRect(10, 365, 131, 19))
        self.StrongBodyLabel_4.setObjectName("StrongBodyLabel_4")
        self.hw = LineEdit(self.CardWidget)
        self.hw.setGeometry(QtCore.QRect(200, 410, 161, 40))
        self.hw.setReadOnly(True)
        self.hw.setObjectName("hw")
        self.StrongBodyLabel_5 = StrongBodyLabel(self.CardWidget)
        self.StrongBodyLabel_5.setGeometry(QtCore.QRect(10, 415, 131, 19))
        self.StrongBodyLabel_5.setObjectName("StrongBodyLabel_5")
        self.sw = LineEdit(self.CardWidget)
        self.sw.setGeometry(QtCore.QRect(200, 360, 161, 40))
        self.sw.setReadOnly(True)
        self.sw.setObjectName("sw")
        self.button_input = PrimaryPushButton(self.CardWidget)
        self.button_input.setGeometry(QtCore.QRect(270, 520, 91, 31))
        self.button_input.setMaximumWidth(70)
        self.button_input.setStyleSheet("PushButton, ToolButton, ToggleButton, ToggleToolButton {\n"
                                        "    color: black;\n"
                                        "    background: rgba(255, 255, 255, 0.7);\n"
                                        "    border: 1px solid rgba(0, 0, 0, 0.073);\n"
                                        "    border-bottom: 1px solid rgba(0, 0, 0, 0.183);\n"
                                        "    border-radius: 15px;\n"
                                        "    /* font: 14px \'Segoe UI\', \'Microsoft YaHei\'; */\n"
                                        "    padding: 5px 12px 6px 12px;\n"
                                        "    font-size: 13px;\n"
                                        "    font-weight:bold;\n"
                                        "    outline: none;\n"
                                        "}\n"
                                        "PushButton[hasIcon=false] {\n"
                                        "    padding: 5px 12px 6px 12px;\n"
                                        "}\n"
                                        "PushButton[hasIcon=true] {\n"
                                        "    padding: 5px 12px 6px 36px;\n"
                                        "}\n"
                                        "PushButton:hover, ToolButton:hover, ToggleButton:hover, ToggleToolButton:hover {\n"
                                        "    background: rgba(249, 249, 249, 0.5);\n"
                                        "}\n"
                                        "PushButton:pressed, ToolButton:pressed, ToggleButton:pressed, ToggleToolButton:pressed {\n"
                                        "    color: rgba(0, 0, 0, 0.63);\n"
                                        "    background: rgba(249, 249, 249, 0.3);\n"
                                        "    border-bottom: 1px solid rgba(0, 0, 0, 0.073);\n"
                                        "}\n"
                                        "PushButton:disabled, ToolButton:disabled, ToggleButton:disabled, ToggleToolButton:disabled {\n"
                                        "    color: rgba(0, 0, 0, 0.36);\n"
                                        "    background: rgba(249, 249, 249, 0.3);\n"
                                        "    border: 1px solid rgba(0, 0, 0, 0.06);\n"
                                        "    border-bottom: 1px solid rgba(0, 0, 0, 0.06);\n"
                                        "}\n"
                                        "PrimaryPushButton,\n"
                                        "PrimaryToolButton,\n"
                                        "ToggleButton:checked,\n"
                                        "ToggleToolButton:checked {\n"
                                        "    color: white;\n"
                                        "    background-color: #009faa;\n"
                                        "    border: 1px solid #00a7b3;\n"
                                        "    border-bottom: 1px solid #007780;\n"
                                        "}\n"
                                        "PrimaryPushButton:hover,\n"
                                        "PrimaryToolButton:hover,\n"
                                        "ToggleButton:checked:hover,\n"
                                        "ToggleToolButton:checked:hover {\n"
                                        "    background-color: #00a7b3;\n"
                                        "    border: 1px solid #2daab3;\n"
                                        "    border-bottom: 1px solid #007780;\n"
                                        "}\n"
                                        "PrimaryPushButton:pressed,\n"
                                        "PrimaryToolButton:pressed,\n"
                                        "ToggleButton:checked:pressed,\n"
                                        "ToggleToolButton:checked:pressed {\n"
                                        "    color: rgba(255, 255, 255, 0.63);\n"
                                        "    background-color: #3eabb3;\n"
                                        "    border: 1px solid #3eabb3;\n"
                                        "}\n"
                                        "PrimaryPushButton:disabled,\n"
                                        "PrimaryToolButton:disabled,\n"
                                        "ToggleButton:checked:disabled,\n"
                                        "ToggleToolButton:checked:disabled {\n"
                                        "    color: rgba(255, 255, 255, 0.9);\n"
                                        "    background-color: rgb(205, 205, 205);\n"
                                        "    border: 1px solid rgb(205, 205, 205);\n"
                                        "}")
        self.button_input.setObjectName("button_input")
        self.input_text = LineEdit(self.CardWidget)
        self.input_text.setMinimumWidth(231)
        self.input_text.setGeometry(QtCore.QRect(10, 520, 231, 40))
        self.input_text.setText("")
        self.input_text.setReadOnly(False)
        self.input_text.setObjectName("input_text")

        subLayout_1 = QFormLayout(self.CardWidget)
        subLayout_1.addRow(self.StrongBodyLabel, self.model)
        subLayout_1.addRow(self.StrongBodyLabel_2, self.brand)
        subLayout_1.addRow(self.StrongBodyLabel_3, self.android_version)
        subLayout_1.addRow(self.StrongBodyLabel_8, self.sn)
        subLayout_1.addRow(self.StrongBodyLabel_9, self.mac)
        subLayout_1.addRow(self.StrongBodyLabel_6, self.fingerprint)
        subLayout_1.addRow(self.StrongBodyLabel_7, self.ipv4)
        subLayout_1.addRow(self.StrongBodyLabel_4, self.sw)
        subLayout_1.addRow(self.StrongBodyLabel_5, self.hw)
        subLayout_1.addRow(self.search_prop, self.output_prop)
        subLayout_1.addRow(self.input_text, self.button_input)


        self.CardWidget_2 = CardWidget(Form)
        self.CardWidget_2.setGeometry(QtCore.QRect(370, 0, 651, 581))
        self.CardWidget_2.setObjectName("CardWidget_2")
        self.StrongBodyLabel_15 = StrongBodyLabel(self.CardWidget_2)
        self.StrongBodyLabel_15.setGeometry(QtCore.QRect(20, 360, 71, 19))
        self.StrongBodyLabel_15.setStyleSheet("font-weight:bold;\n"
                                              "")
        self.StrongBodyLabel_15.setObjectName("StrongBodyLabel_15")
        self.StrongBodyLabel_14 = StrongBodyLabel(self.CardWidget_2)
        self.StrongBodyLabel_14.setGeometry(QtCore.QRect(20, 290, 71, 19))
        self.StrongBodyLabel_14.setStyleSheet("font-weight:bold;\n"
                                              "")
        self.StrongBodyLabel_14.setObjectName("StrongBodyLabel_14")
        self.StrongBodyLabel_13 = StrongBodyLabel(self.CardWidget_2)
        self.StrongBodyLabel_13.setGeometry(QtCore.QRect(20, 220, 71, 19))
        self.StrongBodyLabel_13.setStyleSheet("font-weight:bold;\n"
                                              "")
        self.StrongBodyLabel_13.setObjectName("StrongBodyLabel_13")
        self.StrongBodyLabel_12 = StrongBodyLabel(self.CardWidget_2)
        self.StrongBodyLabel_12.setGeometry(QtCore.QRect(20, 160, 71, 19))
        self.StrongBodyLabel_12.setStyleSheet("font-weight:bold;\n"
                                              "")
        self.StrongBodyLabel_12.setObjectName("StrongBodyLabel_12")
        self.StrongBodyLabel_11 = StrongBodyLabel(self.CardWidget_2)
        self.StrongBodyLabel_11.setGeometry(QtCore.QRect(20, 100, 71, 19))
        self.StrongBodyLabel_11.setStyleSheet("font-weight:bold;\n"
                                              "")
        self.StrongBodyLabel_11.setObjectName("StrongBodyLabel_11")
        self.StrongBodyLabel_10 = StrongBodyLabel(self.CardWidget_2)
        self.StrongBodyLabel_10.setGeometry(QtCore.QRect(20, 40, 71, 19))
        self.StrongBodyLabel_10.setStyleSheet("font-weight:bold;\n"
                                              "")
        self.StrongBodyLabel_10.setObjectName("StrongBodyLabel_10")
        self.show_6 = TextEdit(self.CardWidget_2)
        self.show_6.setGeometry(QtCore.QRect(100, 350, 391, 41))
        self.show_6.setReadOnly(True)
        self.show_6.setObjectName("show_6")
        self.show_3 = LineEdit(self.CardWidget_2)
        self.show_3.setGeometry(QtCore.QRect(100, 150, 391, 41))
        self.show_3.setMinimumSize(QtCore.QSize(0, 41))
        self.show_3.setMaximumSize(QtCore.QSize(16777215, 41))
        self.show_3.setText("")
        self.show_3.setReadOnly(True)
        self.show_3.setObjectName("show_3")
        self.show_2 = LineEdit(self.CardWidget_2)
        self.show_2.setGeometry(QtCore.QRect(100, 90, 391, 41))
        self.show_2.setMinimumSize(QtCore.QSize(0, 41))
        self.show_2.setMaximumSize(QtCore.QSize(16777215, 41))
        self.show_2.setText("")
        self.show_2.setReadOnly(True)
        self.show_2.setObjectName("show_2")
        self.show_1 = LineEdit(self.CardWidget_2)
        self.show_1.setGeometry(QtCore.QRect(100, 30, 391, 41))
        self.show_1.setMinimumSize(QtCore.QSize(0, 41))
        self.show_1.setMaximumSize(QtCore.QSize(16777215, 41))
        self.show_1.setText("")
        self.show_1.setReadOnly(True)
        self.show_1.setObjectName("show_1")
        self.button_refresh = PrimaryPushButton(self.CardWidget_2)
        self.button_refresh.setGeometry(QtCore.QRect(20, 510, 50, 50))
        self.button_refresh.setMinimumSize(QtCore.QSize(50, 50))
        self.button_refresh.setMaximumSize(QtCore.QSize(50, 50))
        self.button_refresh.setStyleSheet("PushButton, ToolButton, ToggleButton, ToggleToolButton {\n"
                                          "    color: black;\n"
                                          "    background: rgba(255, 255, 255, 0.7);\n"
                                          "    border: 1px solid rgba(0, 0, 0, 0.073);\n"
                                          "    border-bottom: 1px solid rgba(0, 0, 0, 0.183);\n"
                                          "    border-radius: 25px;\n"
                                          "    /* font: 14px \'Segoe UI\', \'Microsoft YaHei\'; */\n"
                                          "    padding: 5px 12px 6px 12px;\n"
                                          "    font-size:1px;\n"
                                          "    outline: none;\n"
                                          "}\n"
                                          "PushButton[hasIcon=false] {\n"
                                          "    padding: 5px 12px 6px 12px;\n"
                                          "}\n"
                                          "PushButton[hasIcon=true] {\n"
                                          "    padding: 5px 12px 6px 36px;\n"
                                          "}\n"
                                          "PushButton:hover, ToolButton:hover, ToggleButton:hover, ToggleToolButton:hover {\n"
                                          "    background: rgba(249, 249, 249, 0.5);\n"
                                          "}\n"
                                          "PushButton:pressed, ToolButton:pressed, ToggleButton:pressed, ToggleToolButton:pressed {\n"
                                          "    color: rgba(0, 0, 0, 0.63);\n"
                                          "    background: rgba(249, 249, 249, 0.3);\n"
                                          "    border-bottom: 1px solid rgba(0, 0, 0, 0.073);\n"
                                          "}\n"
                                          "PushButton:disabled, ToolButton:disabled, ToggleButton:disabled, ToggleToolButton:disabled {\n"
                                          "    color: rgba(0, 0, 0, 0.36);\n"
                                          "    background: rgba(249, 249, 249, 0.3);\n"
                                          "    border: 1px solid rgba(0, 0, 0, 0.06);\n"
                                          "    border-bottom: 1px solid rgba(0, 0, 0, 0.06);\n"
                                          "}\n"
                                          "PrimaryPushButton,\n"
                                          "PrimaryToolButton,\n"
                                          "ToggleButton:checked,\n"
                                          "ToggleToolButton:checked {\n"
                                          "    color: white;\n"
                                          "    background-color: #009faa;\n"
                                          "    border: 1px solid #00a7b3;\n"
                                          "    border-bottom: 1px solid #007780;\n"
                                          "}\n"
                                          "PrimaryPushButton:hover,\n"
                                          "PrimaryToolButton:hover,\n"
                                          "ToggleButton:checked:hover,\n"
                                          "ToggleToolButton:checked:hover {\n"
                                          "    background-color: #00a7b3;\n"
                                          "    border: 1px solid #2daab3;\n"
                                          "    border-bottom: 1px solid #007780;\n"
                                          "}\n"
                                          "PrimaryPushButton:pressed,\n"
                                          "PrimaryToolButton:pressed,\n"
                                          "ToggleButton:checked:pressed,\n"
                                          "ToggleToolButton:checked:pressed {\n"
                                          "    color: rgba(255, 255, 255, 0.63);\n"
                                          "    background-color: #3eabb3;\n"
                                          "    border: 1px solid #3eabb3;\n"
                                          "}\n"
                                          "PrimaryPushButton:disabled,\n"
                                          "PrimaryToolButton:disabled,\n"
                                          "ToggleButton:checked:disabled,\n"
                                          "ToggleToolButton:checked:disabled {\n"
                                          "    color: rgba(255, 255, 255, 0.9);\n"
                                          "    background-color: rgb(205, 205, 205);\n"
                                          "    border: 1px solid rgb(205, 205, 205);\n"
                                          "}")
        self.button_refresh.setText("")
        self.button_refresh.setObjectName("button_refresh")
        self.show_5 = TextEdit(self.CardWidget_2)
        self.show_5.setGeometry(QtCore.QRect(100, 280, 391, 41))
        self.show_5.setReadOnly(True)
        self.show_5.setObjectName("show_5")
        self.show_4 = TextEdit(self.CardWidget_2)
        self.show_4.setGeometry(QtCore.QRect(100, 210, 391, 41))
        self.show_4.setReadOnly(True)
        self.show_4.setObjectName("show_4")
        subLayout_2 = QFormLayout(self.CardWidget_2)
        subLayout_2.addRow(self.StrongBodyLabel_10, self.show_1)
        subLayout_2.addRow(self.StrongBodyLabel_11, self.show_2)
        subLayout_2.addRow(self.StrongBodyLabel_12, self.show_3)
        subLayout_2.addRow(self.StrongBodyLabel_13, self.show_4)
        subLayout_2.addRow(self.StrongBodyLabel_14, self.show_5)
        subLayout_2.addRow(self.StrongBodyLabel_15, self.show_6)
        subLayout_2.addRow(self.button_refresh, None)

        layout.addWidget(self.CardWidget)
        layout.addWidget(self.CardWidget_2)
        print("CardWidget Size:", self.CardWidget.size())
        print("CardWidget_2 Size:", self.CardWidget_2.size())

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.StrongBodyLabel.setText(_translate("Form", "Model"))
        self.StrongBodyLabel_2.setText(_translate("Form", "Brand"))
        self.StrongBodyLabel_3.setText(_translate("Form", "Android Version"))
        self.StrongBodyLabel_6.setText(_translate("Form", "FingerPrint"))
        self.StrongBodyLabel_7.setText(_translate("Form", "Ipv4Address"))
        self.model.setText(_translate("Form", "UnKnown"))
        self.brand.setText(_translate("Form", "UnKnown"))
        self.android_version.setText(_translate("Form", "UnKnown"))
        self.fingerprint.setText(_translate("Form", "UnKnown"))
        self.ipv4.setText(_translate("Form", "UnKnown"))
        self.search_prop.setPlaceholderText(_translate("Form", "Prop"))
        self.StrongBodyLabel_8.setText(_translate("Form", "Serial Number"))
        self.sn.setText(_translate("Form", "UnKnown"))
        self.mac.setText(_translate("Form", "UnKnown"))
        self.StrongBodyLabel_9.setText(_translate("Form", "MAC"))
        self.StrongBodyLabel_4.setText(_translate("Form", "Software Version"))
        self.hw.setText(_translate("Form", "UnKnown"))
        self.StrongBodyLabel_5.setText(_translate("Form", "Hardware Version"))
        self.sw.setText(_translate("Form", "UnKnown"))
        self.button_input.setText(_translate("Form", "Input"))
        self.input_text.setPlaceholderText(_translate("Form", "Input Text"))
        self.StrongBodyLabel_15.setText(_translate("Form", "活动堆栈："))
        self.StrongBodyLabel_14.setText(_translate("Form", "上次活动："))
        self.StrongBodyLabel_13.setText(_translate("Form", "前台活动："))
        self.StrongBodyLabel_12.setText(_translate("Form", "启动活动："))
        self.StrongBodyLabel_11.setText(_translate("Form", "当前进程："))
        self.StrongBodyLabel_10.setText(_translate("Form", "当前包名："))


from qfluentwidgets import CardWidget, LineEdit, PrimaryPushButton, SearchLineEdit, StrongBodyLabel, TextEdit
