# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6.QtCore import *  # type: ignore
from PySide6.QtGui import *  # type: ignore
from PySide6.QtWidgets import *  # type: ignore
from PySide6 import QtCore, QtWidgets


class Ui_centralwidget(object):
    def setupUi(self, centralwidget):
        centralwidget.setObjectName("centralwidget")
        centralwidget.resize(800, 600)
        self.CardWidget = CardWidget(centralwidget)
        self.CardWidget.setGeometry(QtCore.QRect(0, 80, 800, 450))
        self.CardWidget.setObjectName("CardWidget")
        self.label = QtWidgets.QLabel(self.CardWidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 800, 450))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.progressRing = IndeterminateProgressRing(self.CardWidget)
        self.progressRing.setGeometry(QtCore.QRect(360, 190, 80, 80))
        self.progressRing.setObjectName("progressRing")
        self.CardWidget_2 = CardWidget(centralwidget)
        self.CardWidget_2.setGeometry(QtCore.QRect(0, 0, 801, 81))
        self.CardWidget_2.setObjectName("CardWidget_2")
        self.button_refresh = PrimaryPushButton(self.CardWidget_2)
        self.button_refresh.setEnabled(True)
        self.button_refresh.setGeometry(QtCore.QRect(390, 20, 72, 32))
        self.button_refresh.setObjectName("button_refresh")
        self.BodyLabel = BodyLabel(self.CardWidget_2)
        self.BodyLabel.setGeometry(QtCore.QRect(490, 20, 71, 24))
        self.BodyLabel.setProperty("pixelFontSize", 18)
        self.BodyLabel.setObjectName("BodyLabel")
        self.combo_device = ComboBox(self.CardWidget_2)
        self.combo_device.setGeometry(QtCore.QRect(570, 20, 111, 32))
        self.combo_device.setObjectName("combo_device")
        self.flip = CheckBox(self.CardWidget_2)
        self.flip.setGeometry(QtCore.QRect(490, 50, 77, 22))
        self.flip.setObjectName("flip")
        self.button_start = PrimaryPushButton(self.CardWidget_2)
        self.button_start.setGeometry(QtCore.QRect(700, 20, 81, 32))
        self.button_start.setObjectName("button_start")
        self.ipInput = LineEdit(self.CardWidget_2)
        self.ipInput.setGeometry(QtCore.QRect(90, 20, 141, 33))
        self.ipInput.setInputMask("")
        self.ipInput.setText("")
        self.ipInput.setObjectName("ipInput")
        self.BodyLabel_2 = BodyLabel(self.CardWidget_2)
        self.BodyLabel_2.setGeometry(QtCore.QRect(10, 30, 71, 19))
        self.BodyLabel_2.setProperty("pixelFontSize", 16)
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.button_connect = PrimaryPushButton(self.CardWidget_2)
        self.button_connect.setGeometry(QtCore.QRect(250, 20, 91, 31))
        self.button_connect.setObjectName("button_connect")
        self.VerticalSeparator = VerticalSeparator(self.CardWidget_2)
        self.VerticalSeparator.setGeometry(QtCore.QRect(360, 10, 3, 61))
        self.VerticalSeparator.setObjectName("VerticalSeparator")
        self.CardWidget_3 = CardWidget(centralwidget)
        self.CardWidget_3.setGeometry(QtCore.QRect(0, 530, 800, 70))
        self.CardWidget_3.setObjectName("CardWidget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.CardWidget_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.button_home = PushButton(self.CardWidget_3)
        self.button_home.setObjectName("button_home")
        self.horizontalLayout.addWidget(self.button_home)
        self.button_back = PushButton(self.CardWidget_3)
        self.button_back.setObjectName("button_back")
        self.horizontalLayout.addWidget(self.button_back)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)

        self.retranslateUi(centralwidget)
        QtCore.QMetaObject.connectSlotsByName(centralwidget)

    def retranslateUi(self, centralwidget):
        _translate = QtCore.QCoreApplication.translate
        centralwidget.setWindowTitle(_translate("centralwidget", "Form"))
        self.label.setText(_translate("centralwidget", "Loading"))
        self.button_refresh.setText(_translate("centralwidget", "Refresh"))
        self.BodyLabel.setText(_translate("centralwidget", "Devices："))
        self.flip.setText(_translate("centralwidget", "Reverse"))
        self.button_start.setText(_translate("centralwidget", "Start"))
        self.ipInput.setPlaceholderText(_translate("centralwidget", "ip:port"))
        self.BodyLabel_2.setText(_translate("centralwidget", "ADB WIFI:"))
        self.button_connect.setText(_translate("centralwidget", "Connect"))
        self.button_home.setText(_translate("centralwidget", "HOME"))
        self.button_back.setText(_translate("centralwidget", "BACK"))
from qfluentwidgets import BodyLabel, CardWidget, CheckBox, ComboBox, IndeterminateProgressRing, LineEdit, PrimaryPushButton, PushButton, VerticalSeparator
